//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.07 at 10:27:01 AM ICT 
//


package id.go.pajak.enkripsi.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NoSrPermintaan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NamaFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetailType", propOrder = {
    "noSrPermintaan",
    "namaFile"
})
public class DetailType {

    @XmlElement(name = "NoSrPermintaan", required = true)
    protected String noSrPermintaan;
    @XmlElement(name = "NamaFile", required = true)
    protected String namaFile;

    /**
     * Gets the value of the noSrPermintaan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoSrPermintaan() {
        return noSrPermintaan;
    }

    /**
     * Sets the value of the noSrPermintaan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoSrPermintaan(String value) {
        this.noSrPermintaan = value;
    }

    /**
     * Gets the value of the namaFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamaFile() {
        return namaFile;
    }

    /**
     * Sets the value of the namaFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamaFile(String value) {
        this.namaFile = value;
    }

}
