//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.07 at 10:27:01 AM ICT 
//


package id.go.pajak.enkripsi.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Npwp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NamaLjk" type="{}nameType"/>
 *         &lt;element name="JumlahFile" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderType", propOrder = {
    "npwp",
    "namaLjk",
    "jumlahFile"
})
public class HeaderType {

    @XmlElement(name = "Npwp", required = true)
    protected String npwp;
    @XmlElement(name = "NamaLjk", required = true)
    protected String namaLjk;
    @XmlElement(name = "JumlahFile", required = true)
    protected BigDecimal jumlahFile;

    /**
     * Gets the value of the npwp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpwp() {
        return npwp;
    }

    /**
     * Sets the value of the npwp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpwp(String value) {
        this.npwp = value;
    }

    /**
     * Gets the value of the namaLjk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamaLjk() {
        return namaLjk;
    }

    /**
     * Sets the value of the namaLjk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamaLjk(String value) {
        this.namaLjk = value;
    }

    /**
     * Gets the value of the jumlahFile property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getJumlahFile() {
        return jumlahFile;
    }

    /**
     * Sets the value of the jumlahFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setJumlahFile(BigDecimal value) {
        this.jumlahFile = value;
    }

}
