//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.07 at 10:27:01 AM ICT 
//


package id.go.pajak.enkripsi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.go.pajak.model.manifest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Manifest_QNAME = new QName("", "manifest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.go.pajak.model.manifest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MainType }
     * 
     */
    public MainType createMainType() {
        return new MainType();
    }

    /**
     * Create an instance of {@link DetailType }
     * 
     */
    public DetailType createDetailType() {
        return new DetailType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "manifest")
    public JAXBElement<MainType> createManifest(MainType value) {
        return new JAXBElement<MainType>(_Manifest_QNAME, MainType.class, null, value);
    }

}
